Fix compilation error: use Montserrat 32 instead of 28
Montserrat 28 font is not available in LVGL configuration.
Changed to Montserrat 32 which is the next available size.

Labels "1/2" and "3/11" now use lv_font_montserrat_32.